[hewg]
version =  "0.4.0-alpha.nd"
type = "executable"

[project]
version = "0.0.1"
org = "crow"
name = "ccc_crowcpu_ld"
description = ""
authors = { }

[depends]
internal = { 
	"=crow.POFF_c-0.1.0" 
	"=crow.crowcpu_arch-0.1.0" 
	"=crow.brbt-0.4.0"
}
external = { }

[cxx]
flags = { "-Wall" "-Wextra" "-Werror" }
std = 23
sources = { }

[c]
flags = { "-D_POSIX_C_SOURCE=200809L" "-Wall" "-Wextra" }
std = 17
sources = { 
	"main.c" 
	"script.c"
	"symbol.c"
	"y.tab.c"
	"lex.yy.c"
}

[hooks.prebuild]
[hooks.postbuild]
